-- Smooth monthly statistics for the "Evoluția rezultatelor" charts.
--
-- For every school/category/year that has a yearly row (period_month = 0), this writes
-- monthly rows 1–12 (for the current year: every completed month, plus any month that
-- already exists) whose pass rates follow the yearly level with a gentle trend, one
-- seasonal wave and small occasional fluctuations. Theory rates stay inside (80%, 95%).
--
-- * Yearly rows (period_month = 0) are never modified.
-- * Only source counts are written; the *_rate columns are generated by PostgreSQL.
-- * Deterministic (hash-based, no random()), so re-running gives the same data.
--
-- Apply:  python -m scripts.run_sql ../database/seed/monthly_statistics.sql   (from backend/)
--    or:  psql -U postgres -d postgresql -f database/seed/monthly_statistics.sql

BEGIN;

WITH yearly AS (
    SELECT y.school_id,
           y.category_code,
           y.period_year,
           y.school_id || '/' || y.category_code || '/' || y.period_year AS series,
           coalesce(y.theory_pass_rate, 88)                                     AS theory_base,
           coalesce(y.theory_first_attempt_rate, y.theory_pass_rate, 84)        AS theory_first_base,
           coalesce(y.practice_pass_rate, 68)                                   AS practice_base,
           coalesce(y.practice_first_attempt_rate, y.practice_pass_rate, 62)    AS practice_first_base,
           -- at least ~120 attempts a month, so rounding moves a rate by 0.5 points at most
           greatest(118, y.theory_attempts / 12.0)                              AS theory_volume,
           greatest(118, y.practice_attempts / 12.0)                            AS practice_volume,
           coalesce(y.avg_attempts_to_pass, 1.4)                                AS attempts_base,
           coalesce(y.avg_penalty_points, 12)                                   AS penalty_base,
           y.avg_rating
    FROM statistici_scoli_perioade y
    WHERE y.period_month = 0
),
params AS (
    -- Per-series curve shape: trend over the year (±1.2 points), wave amplitude and phase
    SELECT yr.*,
           ((abs(hashtext(series || ':trend')) % 1000) / 1000.0 - 0.5) * 2.4 AS trend,
           0.8 + (abs(hashtext(series || ':amp')) % 1000) / 1000.0            AS amplitude,
           abs(hashtext(series || ':phase')) % 12                             AS phase
    FROM yearly yr
),
months AS (
    SELECT p.*, m.month
    FROM params p
    CROSS JOIN LATERAL generate_series(1, CASE
        WHEN p.period_year < extract(year FROM current_date) THEN 12
        WHEN p.period_year > extract(year FROM current_date) THEN 0
        ELSE greatest(extract(month FROM current_date)::int - 1, (
            SELECT coalesce(max(e.period_month), 0)
            FROM statistici_scoli_perioade e
            WHERE e.school_id = p.school_id
              AND e.category_code = p.category_code
              AND e.period_year = p.period_year))
    END) AS m(month)
),
shaped AS (
    SELECT ms.*,
           trend * (month - 6.5) / 5.5
             + amplitude * sin(2 * pi() * (month + phase) / 12)::numeric           AS wave,
           ((abs(hashtext(series || ':j' || month)) % 1000) / 1000.0 - 0.5) * 0.6 AS jitter,
           CASE WHEN abs(hashtext(series || ':o' || month)) % 9 = 0
                THEN ((abs(hashtext(series || ':v' || month)) % 1000) / 1000.0 - 0.5) * 1.8
                ELSE 0 END                                                         AS blip,
           1 + 0.15 * sin(2 * pi() * (month - 3) / 12)::numeric                    AS season
    FROM months ms
),
rates AS (
    SELECT s.*,
           least(94.4, greatest(80.6, theory_base + wave + jitter + blip))            AS theory,
           least(95, greatest(40, practice_first_base + 1.3 * wave + jitter))         AS practice_first,
           least(90, greatest(45, practice_base + 1.3 * wave + jitter + blip))        AS practice,
           round(theory_volume * season)                                              AS t_attempts,
           round(practice_volume * season)                                            AS p_attempts
    FROM shaped s
),
theory AS (
    SELECT r.*,
           least(r.theory, greatest(70, theory_first_base + 0.8 * wave + jitter)) AS theory_first,
           round(t_attempts * r.theory / 100)                                     AS t_passed,
           round(p_attempts * practice / 100)                                     AS p_passed
    FROM rates r
),
counts AS (
    SELECT t.*,
           greatest(t_passed, round(t_attempts * (t.theory / 100 + (1 - t.theory / 100) * 0.5)))  AS t_exams,
           greatest(p_passed, round(p_attempts * (practice / 100 + (1 - practice / 100) * 0.35))) AS p_exams
    FROM theory t
)
INSERT INTO statistici_scoli_perioade (
    school_id, category_code, period_year, period_month, candidates_total,
    theory_exams, theory_attempts, theory_passed, theory_first_attempt_passed,
    practice_exams, practice_attempts, practice_passed, practice_first_attempt_passed,
    avg_attempts_to_pass, avg_penalty_points, avg_rating, reviews_count, calculated_at
)
SELECT school_id, category_code, period_year, month,
       round(greatest(t_exams, p_exams) * 1.05),
       t_exams, t_attempts, t_passed, least(t_passed, round(t_exams * theory_first / 100)),
       p_exams, p_attempts, p_passed, least(p_passed, round(p_exams * practice_first / 100)),
       round(greatest(1, attempts_base - 0.02 * wave), 2),
       round(greatest(0, penalty_base - 0.3 * wave), 2),
       avg_rating, 0, now()
FROM counts
ON CONFLICT (school_id, category_code, period_year, period_month) DO UPDATE SET
    candidates_total              = EXCLUDED.candidates_total,
    theory_exams                  = EXCLUDED.theory_exams,
    theory_attempts               = EXCLUDED.theory_attempts,
    theory_passed                 = EXCLUDED.theory_passed,
    theory_first_attempt_passed   = EXCLUDED.theory_first_attempt_passed,
    practice_exams                = EXCLUDED.practice_exams,
    practice_attempts             = EXCLUDED.practice_attempts,
    practice_passed               = EXCLUDED.practice_passed,
    practice_first_attempt_passed = EXCLUDED.practice_first_attempt_passed,
    avg_attempts_to_pass          = EXCLUDED.avg_attempts_to_pass,
    avg_penalty_points            = EXCLUDED.avg_penalty_points,
    calculated_at                 = EXCLUDED.calculated_at;

-- Monthly ranks follow the new figures (same blend as the yearly ranking); yearly rows untouched
UPDATE statistici_scoli_perioade st
   SET rank_position = r.rank
  FROM (
      SELECT school_id, category_code, period_year, period_month,
             row_number() OVER (
                 PARTITION BY category_code, period_year, period_month
                 ORDER BY 0.3 * coalesce(theory_pass_rate, 0)
                        + 0.4 * coalesce(practice_pass_rate, 0)
                        + 0.3 * coalesce(practice_first_attempt_rate, 0) DESC,
                          candidates_total DESC, school_id
             ) AS rank
      FROM statistici_scoli_perioade
      WHERE period_month > 0
  ) r
 WHERE st.period_month > 0
   AND (st.school_id, st.category_code, st.period_year, st.period_month)
     = (r.school_id, r.category_code, r.period_year, r.period_month);

COMMIT;
